# Core and SDK basic settings
CONFIG_DEVICE_ID="MIMX8ML8"
CONFIG_BOARD_ID="evkmimx8mp"

# Enable Multi-core communication
CONFIG_COMPONENT_MULTICORE_RPMSG_LITE=y
CONFIG_COMPONENT_MULTICORE_RPMSG_LITE_FREE_RTOS=y

# Enable FreeRTOS
CONFIG_COMPONENT_OS_FREE_RTOS=y

# Standard SDK components
CONFIG_COMPONENT_SDK_DEBUG_CONSOLE=y
CONFIG_COMPONENT_SDK_COMMON=y
